name: coba
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/referal.png
  - assets/imageprofile.jpg
  - assets/lunch.png
  - assets/dinner.png
  - assets/event.png
  - assets/banner1.jpg
  - assets/banner2.jpg
  - assets/banner3.jpg
  - assets/banner4.jpg
  - assets/nusantara.png
  - assets/western.png
  - assets/japanese.png
  - assets/chinese.png
  - assets/healthy.png
  - assets/oriental.png
  - assets/harga1.png
  - assets/harga2.png
  - assets/harga3.png
  - assets/harga4.png
  - assets/merchant1.png
  - assets/merchant2.jpg
  - assets/merchant3.jpg
  - assets/merchant4.jpg
  - assets/merchant11.jpg
  - assets/merchant22.jpg
  - assets/merchant33.jpg
  - assets/merchant44.jpg
  - assets/kulinamerah.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: present
      fonts:
        - asset: assets/fonts/ic_present.ttf

    - family: wallet
      fonts:
        - asset: assets/fonts/ic_wallet.ttf

    - family: bag
      fonts:
        - asset: assets/fonts/ic_bag.ttf

    - family: home
      fonts:
        - asset: assets/fonts/ic_home.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
